[package]
name = "data-stream-creator"
version = "0.1.0"
edition = "2021"

[dependencies]
amiquip = { version = "0.4", default-features = false }
serde_json = "1.0"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.53"
futures = "0.3.21"